# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-thse-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cells, Generators, and Lenses
theme: minima
description: "Design Framework for Object-Oriented Interaction with Large Language Models"

syscolor: "#0066FF"
sysfont: Lato
video: https://www.youtube.com/embed/_Y0d_uyA6XA
paper: https://kixlab.github.io/website-files/2023/uist2023-llmobjects-paper.pdf
code: https://github.com/kixlab/llm-ui-objects

introduction: "<span style='color: #0066FF;'><b>Cells, Generators, and Lenses</b></span> is a design framework for LLM-powered writing interfaces that <b>modularizes</b> the components of generation configurations (e.g., input, model parameters, output spaces) into <b>interactive objects</b>. The framework aims to <b>guide</b> the design of interfaces that support end-users' <b>iteration and experimentation</b> with LLM configurations while writing with LLMs.<br/><br/>We introduce three interfaces designed through the framework for different writing tasks: <b>copywriting</b>, <b>email composing</b>, and <b>story writing</b>. To facilitate the adoption of the framework, we package the UI components developed for the interactive objects into a <b>ReactJS library</b>."

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
